#!/usr/bin/env python
import os
import sys

env = SConscript("../../godot_cpp/SConstruct")
env.Append(SHCXXCOMSTR=["compiling $SOURCE ..."])
env.Append(SHLINKCOMSTR=["linking $TARGET ..."])
env.Append(CXXFLAGS=["/D_HAS_EXCEPTIONS=0"])
env.Append(CPPPATH=["../../sim/include"])
env.Append(LIBPATH=["../../sim/zig-out/lib"])
env.Append(LIBS=["kirby_sim", "ntdll"])

sources = ["register_types.cpp", "godot_sim.cpp"]
prefix = "../../godot_project/godot_sim/"
libname = "libgodotsim"
library = env.SharedLibrary(
    (prefix + libname + "{}{}").format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)

Default(library)
