#!/usr/bin/env python
import os
import sys

env = SConscript("../../godot_cpp/SConstruct")
sources = ["register_types.cpp", "godot_sim.cpp"]
prefix = "../../godot_project/godot_sim/"
libname = "libgodotsim"

if env["platform"] == "macos":
    library = env.SharedLibrary(
        (prefix + libname + ".{}.{}.framework/" + libname + ".{}.{}").format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        (prefix + libname + "{}{}").format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
